import {
  Archive,
  Bell,
  BookOpen,
  Bookmark,
  Briefcase,
  Calendar,
  Camera,
  Cloud,
  Code,
  Coffee,
  Cpu,
  Database,
  FileText,
  Folder,
  Gamepad2,
  Globe,
  Hammer,
  Heart,
  Home,
  Laptop,
  Layers,
  Lightbulb,
  Link as LinkIcon,
  Mail,
  Map as MapIcon,
  Music,
  Palette,
  Pin,
  Plane,
  Rocket,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  Sparkles,
  Star,
  Terminal,
  Users,
  Wrench,
  Zap,
  type LucideIcon
} from "lucide-react";
import type { WorkspaceIconKey } from "../types";

const ICONS: Record<WorkspaceIconKey, LucideIcon> = {
  briefcase: Briefcase,
  code: Code,
  palette: Palette,
  "book-open": BookOpen,
  rocket: Rocket,
  star: Star,
  globe: Globe,
  folder: Folder,
  search: Search,
  archive: Archive,
  settings: Settings,
  pin: Pin,
  home: Home,
  laptop: Laptop,
  terminal: Terminal,
  database: Database,
  cpu: Cpu,
  calendar: Calendar,
  mail: Mail,
  camera: Camera,
  music: Music,
  gamepad: Gamepad2,
  heart: Heart,
  coffee: Coffee,
  lightbulb: Lightbulb,
  users: Users,
  shield: Shield,
  cloud: Cloud,
  layers: Layers,
  bookmark: Bookmark,
  wrench: Wrench,
  hammer: Hammer,
  shopping: ShoppingBag,
  map: MapIcon,
  plane: Plane,
  "file-text": FileText,
  link: LinkIcon,
  bell: Bell,
  zap: Zap,
  sparkles: Sparkles
};

export function WorkspaceIcon({ iconKey, size = 16 }: { iconKey: WorkspaceIconKey; size?: number }) {
  const Icon = ICONS[iconKey] ?? Briefcase;
  return <Icon size={size} />;
}
